name = "mind-palace-ai-gateway"
main = "src/index.js"
compatibility_date = "2026-04-06"

[[d1_databases]]
binding = "AI_DB"
database_name = "mind-palace-ai-gateway"
database_id = "fd8c84fa-d4c4-4055-887d-6a98e0d206d8"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "752b778324434f848405daf4e805a63f"

[vars]
OPENAI_BASE_URL = "https://api.openai.com/v1/chat/completions"
